apiVersion: apps/v1
kind: Deployment
metadata:
  name: crunchy-grafana
spec:
  selector: {}
  template:
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.1.5
        ports:
        - containerPort: 3000
        env:
        - name: GF_PATHS_DATA
          value: /data/grafana/data
        - name: GF_SECURITY_ADMIN_USER__FILE
          value: /conf/admin/username
        - name: GF_SECURITY_ADMIN_PASSWORD__FILE
          value: /conf/admin/password
        - name: PROM_HOST
          value: crunchy-prometheus
        - name: PROM_PORT
          value: "9090"
        - name: GF_SERVER_ROOT_URL
          valueFrom: {configMapKeyRef: {name: "grafana-config", key: "server-root_url"}}
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          valueFrom: {configMapKeyRef: {name: "grafana-config", key: "smtp-host"}}
        - name: GF_SMTP_USER
          valueFrom: {secretKeyRef: {name: "grafana-smtp", key: "user"}}
        - name: GF_SMTP_PASSWORD
          valueFrom: {secretKeyRef: {name: "grafana-smtp", key: "password"}}
        - name: GF_SMTP_FROM_ADDRESS
          value: "no-reply@skillstream.co.uk"
        - name: GF_AUTH_GOOGLE_ENABLED
          value: "true"
        - name: GF_AUTH_GOOGLE_ALLOW_SIGN_UP
          value: "true"
        - name: GF_AUTH_GOOGLE_CLIENT_ID
          valueFrom: {secretKeyRef: {name: grafana-google, key: client-id}}
        - name: GF_AUTH_GOOGLE_CLIENT_SECRET
          valueFrom: {secretKeyRef: {name: grafana-google, key: client-secret}}
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 25
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: grafanadata
        - mountPath: /conf/admin
          name: grafana-admin
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-dashboards
      securityContext:
        fsGroup: 26
        # supplementalGroups:
        # - 65534
      serviceAccountName: grafana
      volumes:
      - name: grafanadata
        persistentVolumeClaim:
          claimName: grafanadata
      - name: grafana-admin
        secret:
          defaultMode: 420
          secretName: grafana-secret
      - name: grafana-datasources
        configMap:
          defaultMode: 420
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          defaultMode: 420
          name: grafana-dashboards
